### ISSUE TITLE
BRI-1 tests fail

### ISSUE THREAD

**Issue by B45man** [ethereum-oasis/baseline#246]
## Expected Behavior
Following the steps outlined in the readme, I expect the command npm test to work successfully.

## Actual Behavior
I get this output: 

```
$ npm test

> base-example@0.0.0 test /home/bas/Source/baseline/examples/bri-1/base-example
> npm run test:startup && sleep 5 && FAUCET_PRIVATE_KEY='\x2d2d2d2d2d424547494e20504750204d4553534147452d2d2d2d2d0a0a7763464d413247736a3455384551726f415241414245712b71763831777657466f7a686774686136715370633954396553746839645a736762576159375475560a6548584c2b732b6b7a676f4e6c74307839752b755647504377414b2f4a707935654d66522b586d44387733354743556f5158424b7252746d39556d4f675a68730a4f754b326c564a6a427079717632775671306d665835354335656e7a47674158356a31734e506938476b5a717a3477694c682b3832374e6a6a6b577831376a2b0a565763593662457069534a35354c55716d71526d6653314b765075354e7573305977493357714d386d4661564b387151496a4f6c4858586e696b456f4e4c612f0a5268525a486a7a567458464c6c44487354634e645469535635346d544b51306d6173776a663232486c6b5470627a776b4878575243366a79752f634664344e580a6f313348422b6b6d5368412f5432633636597a676d6948544e583377456866496643767055596c3174326b4b76754e447647726f314448577739726d4c30476a0a70414e2f575a333641387a4e2f75527a614d7774386d446f49633443327657374a6a36726e73634e4b47524359666c3253496669587267455057584f756645700a4870487a7a46464c66514b396d44455862786375307a4c5a2b435072433073547056464964764c6876384a615a534f377133443276656a7136535061506e6e550a4e4c704c6b49496a49793949344248784d78684b36342f5644325a74573146476c4b396c3351345633672f6c777a73507956563844774b457848732b6631336f0a6c316c7838414a6c49334e61415074454e46524b6f4f4b5445424952624765543834446974556946416e4239514f63336f4e33334170323578423937327968730a5a536e5265775a584377537074395a7a77564e7a44496b51466e616547336c4b5048364a6475434b71482f6377586b795a37793237436c397153756b6f6f58530a3441486a393337444a67784144767668575972676375414734584170344544694f596f32702b4130356a724a6870534c31386374794f587176597534716530770a66792f524f5866782f33366b5a626d443568452b4f583878716e376a5a497a4b4756716e67426d517742514e756c594f6d316d336c73647a4646734b4b7362670a794f525a5a4f764c4a58373250746c7a716b6d6b6f383355346e357341504868545151410a3d547059550a2d2d2d2d2d454e4420504750204d4553534147452d2d2d2d2d' FAUCET_ADDRESS=0x96f1027FEe06A15f42E48180705a2ecB2F846985 ./node_modules/.bin/mocha --require esm --require ts-node/register --require global-jsdom/lib/register test/**/*.spec.ts --timeout 940000 --trace-warnings --unhandled-rejections=strict --max-old-space-size=8192 && npm run test:teardown


> base-example@0.0.0 test:startup /home/bas/Source/baseline/examples/bri-1/base-example
> make start

docker-compose up -d --remove-orphans
alice-provide-nats is up-to-date
bob-provide-nats is up-to-date
alice-postgres is up-to-date
bob-redis is up-to-date
alice-redis is up-to-date
bob-postgres is up-to-date
bob-nethermind is up-to-date
alice-nethermind is up-to-date
alice-nats-streaming is up-to-date
bob-nats-streaming is up-to-date
alice-vault is up-to-date
bob-vault is up-to-date
alice-statsdaemon is up-to-date
alice-ident-consumer is up-to-date
alice-nchain-consumer is up-to-date
alice-nchain is up-to-date
alice-ident is up-to-date
bob-statsdaemon is up-to-date
bob-nchain-consumer is up-to-date
bob-ident is up-to-date
bob-ident-consumer is up-to-date
bob-nchain is up-to-date


  baseline
    1) "before all" hook in "baseline"


  0 passing (68ms)
  1 failing

  1) baseline
       "before all" hook in "baseline":
     Error: Request failed with status code 500
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at XMLHttpRequest.handleLoad (node_modules/axios/lib/adapters/xhr.js:61:7)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:32:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at readyStateChange (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:762:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:888:5)
      at Request.EventEmitter.emit (domain.js:483:12)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at IncomingMessage.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1220:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Steps to Reproduce the Problem

  1. Fork the branch
  2. Run the BRI-1 tests with `npm install` followed by `npm test`.
  3. Bug happens
  4. ????
  5. Profit

## Specifications

  - Version: Latest
  - Platform: Fedora 32
  - Subsystem:

**Comment by kthomas** [comment]
See the `bri-1.1` branch (specifically, try running `ab0cd3e4f5c6faf3346b92c11b7ba23ad31945c3`).

**Comment by B45man** [comment]
Hi @kthomas , thanks for the help. However, the bri-1.1 branch is still giving issues. I did a `git checkout bri-1.1`, deleted all the existing volumes, and ran the commands again, same issue. I don't mean to be rude, but I don't understand what you mean by running `ab0cd3e4f5c6faf3346b92c11b7ba23ad31945c3`.

I took a screenshot of the running docker containers, and the provide/nchain containers all seem to be failling, and restarting constantly: [docker ps outputs this.](https://imgur.com/a/wOOkbZd)

Checking the logs for the failing container at the top I get this:

```
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=warning msg="failed to invoke HTTP POST request: http://alice-ident:8080/api/v1/tokens; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
time="2020-10-21T05:51:01Z" level=warning msg="failed to authorize access token for given vault refresh token; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
time="2020-10-21T05:51:01Z" level=fatal msg="failed to refresh vault access token; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T05:51:01Z" level=warning msg="failed to invoke HTTP POST request: http://alice-ident:8080/api/v1/tokens; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
time="2020-10-21T05:51:01Z" level=warning msg="failed to authorize access token for given vault refresh token; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
time="2020-10-21T05:51:01Z" level=fatal msg="failed to refresh vault access token; Post \"http://alice-ident:8080/api/v1/tokens\": dial tcp 172.40.0.9:8080: connect: connection refused"
```
Looking at the logs for the alice-ident container, I see this:

`await_tcp.sh: waiting 15 seconds for alice-postgres:5432
await_tcp.sh: alice-postgres:5432 is available after 0 seconds
time="2020-10-21T06:00:45Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T06:00:53Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T06:00:53Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T06:00:53Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T06:00:53Z" level=debug msg="using stderr for new logger instance"
time="2020-10-21T06:00:53Z" level=debug msg="user package consumer configured to skip NATS streaming subscription setup"
time="2020-10-21T06:00:53Z" level=debug msg="organization package consumer configured to skip NATS streaming subscription setup"
time="2020-10-21T06:00:53Z" level=debug msg="application package consumer configured to skip NATS streaming subscription setup"
time="2020-10-21T06:00:53Z" level=debug msg="attempting to read required JWT configuration environment for signing JWT tokens"
time="2020-10-21T06:00:53Z" level=debug msg="attempting to read required RS256 keypair(s) from environment for signing JWT tokens"
time="2020-10-21T06:00:53Z" level=debug msg="starting ident API..."
time="2020-10-21T06:00:53Z" level=debug msg="installing signal handlers for ident API"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /status                   --> main.statusHandler (4 handlers)
[GIN-debug] POST   /api/v1/authenticate      --> github.com/provideapp/ident/user.authenticationHandler (4 handlers)
[GIN-debug] POST   /api/v1/users             --> github.com/provideapp/ident/user.createUserHandler (4 handlers)
[GIN-debug] POST   /api/v1/users/reset_password --> github.com/provideapp/ident/user.userResetPasswordRequestHandler (4 handlers)
[GIN-debug] POST   /api/v1/users/reset_password/:token --> github.com/provideapp/ident/user.userResetPasswordHandler (4 handlers)
[GIN-debug] POST   /api/v1/oauth/callback    --> github.com/provideapp/ident/user.oauthCallbackHandler (4 handlers)
[GIN-debug] GET    /api/v1/applications      --> github.com/provideapp/ident/application.applicationsListHandler (8 handlers)
[GIN-debug] POST   /api/v1/applications      --> github.com/provideapp/ident/application.createApplicationHandler (8 handlers)
[GIN-debug] GET    /api/v1/applications/:id  --> github.com/provideapp/ident/application.applicationDetailsHandler (8 handlers)
[GIN-debug] PUT    /api/v1/applications/:id  --> github.com/provideapp/ident/application.updateApplicationHandler (8 handlers)
[GIN-debug] DELETE /api/v1/applications/:id  --> github.com/provideapp/ident/application.deleteApplicationHandler (8 handlers)
[GIN-debug] GET    /api/v1/applications/:id/tokens --> github.com/provideapp/ident/application.applicationTokensListHandler (8 handlers)
[GIN-debug] GET    /api/v1/applications/:id/organizations --> github.com/provideapp/ident/application.applicationOrganizationsListHandler (8 handlers)
[GIN-debug] POST   /api/v1/applications/:id/organizations --> github.com/provideapp/ident/application.createApplicationOrganizationHandler (8 handlers)
[GIN-debug] PUT    /api/v1/applications/:id/organizations/:orgId --> github.com/provideapp/ident/application.updateApplicationOrganizationHandler (8 handlers)
[GIN-debug] DELETE /api/v1/applications/:id/organizations/:orgId --> github.com/provideapp/ident/application.deleteApplicationOrganizationHandler (8 handlers)
[GIN-debug] GET    /api/v1/applications/:id/users --> github.com/provideapp/ident/application.applicationUsersListHandler (8 handlers)
[GIN-debug] POST   /api/v1/applications/:id/users --> github.com/provideapp/ident/application.createApplicationUserHandler (8 handlers)
[GIN-debug] PUT    /api/v1/applications/:id/users/:userId --> github.com/provideapp/ident/application.updateApplicationUserHandler (8 handlers)
[GIN-debug] DELETE /api/v1/applications/:id/users/:userId --> github.com/provideapp/ident/application.deleteApplicationUserHandler (8 handlers)
[GIN-debug] GET    /api/v1/applications/:id/invitations --> github.com/provideapp/ident/application.applicationInvitationsListHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations     --> github.com/provideapp/ident/organization.organizationsListHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id --> github.com/provideapp/ident/organization.organizationDetailsHandler (8 handlers)
[GIN-debug] POST   /api/v1/organizations     --> github.com/provideapp/ident/organization.createOrganizationHandler (8 handlers)
[GIN-debug] PUT    /api/v1/organizations/:id --> github.com/provideapp/ident/organization.updateOrganizationHandler (8 handlers)
[GIN-debug] DELETE /api/v1/organizations/:id --> github.com/provideapp/ident/organization.deleteOrganizationHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id/users --> github.com/provideapp/ident/organization.organizationUsersListHandler (8 handlers)
[GIN-debug] POST   /api/v1/organizations/:id/users --> github.com/provideapp/ident/organization.createOrganizationUserHandler (8 handlers)
[GIN-debug] PUT    /api/v1/organizations/:id/users/:userId --> github.com/provideapp/ident/organization.updateOrganizationUserHandler (8 handlers)
[GIN-debug] DELETE /api/v1/organizations/:id/users/:userId --> github.com/provideapp/ident/organization.deleteOrganizationUserHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id/invitations --> github.com/provideapp/ident/organization.organizationInvitationsListHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id/vaults --> github.com/provideapp/ident/organization.organizationVaultsListHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id/vaults/:vaultId/keys --> github.com/provideapp/ident/organization.organizationVaultKeysListHandler (8 handlers)
[GIN-debug] POST   /api/v1/organizations/:id/vaults/:vaultId/keys --> github.com/provideapp/ident/organization.createOrganizationVaultKeyHandler (8 handlers)
[GIN-debug] POST   /api/v1/organizations/:id/vaults/:vaultId/keys/:keyId/sign --> github.com/provideapp/ident/organization.organizationVaultKeySignHandler (8 handlers)
[GIN-debug] POST   /api/v1/organizations/:id/vaults/:vaultId/keys/:keyId/verify --> github.com/provideapp/ident/organization.organizationVaultKeyVerifyHandler (8 handlers)
[GIN-debug] GET    /api/v1/organizations/:id/vaults/:vaultId/secrets --> github.com/provideapp/ident/organization.organizationVaultSecretsListHandler (8 handlers)
[GIN-debug] GET    /api/v1/tokens            --> github.com/provideapp/ident/token.tokensListHandler (8 handlers)
[GIN-debug] POST   /api/v1/tokens            --> github.com/provideapp/ident/token.createTokenHandler (8 handlers)
[GIN-debug] DELETE /api/v1/tokens/:id        --> github.com/provideapp/ident/token.deleteTokenHandler (8 handlers)
[GIN-debug] GET    /api/v1/users             --> github.com/provideapp/ident/user.usersListHandler (8 handlers)
[GIN-debug] GET    /api/v1/users/:id         --> github.com/provideapp/ident/user.userDetailsHandler (8 handlers)
[GIN-debug] PUT    /api/v1/users/:id         --> github.com/provideapp/ident/user.updateUserHandler (8 handlers)
[GIN-debug] DELETE /api/v1/users/:id         --> github.com/provideapp/ident/user.deleteUserHandler (8 handlers)
[GIN-debug] POST   /api/v1/invitations       --> github.com/provideapp/ident/user.vendInvitationTokenHandler (8 handlers)
time="2020-10-21T06:00:53Z" level=debug msg="listening on 0.0.0.0:8080"
time="2020-10-21T06:00:54Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:54 | 401 |   10.017588ms |     172.40.0.13 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:00:54 | 401 |   15.379454ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:54Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:00:54Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:54 | 401 |    1.396524ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:56 | 401 |    1.503712ms |     172.40.0.11 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:00:56 | 401 |    1.288175ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:56 | 401 |    8.818007ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:56 | 401 |    1.446245ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:00:56 | 401 |    1.420541ms |     172.40.0.12 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:00:56 | 401 |    6.356165ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:00:56Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |    3.169074ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |    1.524133ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:00Z" level=debug msg="created user: alice1603260060516@baseline.local"
[GIN] 2020/10/21 - 06:01:00 | 201 |   71.021467ms |      172.40.0.1 | POST     "/api/v1/users"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |     1.30989ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |    1.262544ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:00Z" level=debug msg="vending signed JWT credential for subject: user:82f17cc0-cf20-460c-a9d6-a14e5b49fca3"
[GIN] 2020/10/21 - 06:01:00 | 201 |   70.683962ms |      172.40.0.1 | POST     "/api/v1/authenticate"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |    1.200573ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:00Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:00 | 401 |    1.150562ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.253083ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.536043ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.359377ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.543882ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.395554ms |     172.40.0.13 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:01:07 | 401 |    1.239038ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:07Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:01:20Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:20 | 401 |    1.608638ms |     172.40.0.11 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:01:20 | 401 |    1.620271ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:20Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:01:20Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:20 | 401 |    2.405146ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:20Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:20 | 401 |    1.185599ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:21Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:21 | 401 |    1.265199ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:21Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:21 | 401 |    1.475223ms |     172.40.0.13 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:01:45 | 200 |       54.41µs |      172.40.0.9 | GET      "/status"
[GIN] 2020/10/21 - 06:01:45 | 200 |      26.969µs |     172.40.0.10 | GET      "/status"
time="2020-10-21T06:01:46Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:46 | 401 |    1.566251ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:46Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:46 | 401 |    1.502963ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:46Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:46 | 401 |    1.503826ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:46Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:46 | 401 |    1.276874ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:47Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:47 | 401 |    1.359665ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:01:47Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:01:47 | 401 |    1.866627ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:38Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:38 | 401 |     1.26642ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:38Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:38 | 401 |    1.183261ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:38Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:38 | 401 |    1.115317ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:38Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:38 | 401 |    1.486061ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:39 | 401 |    1.404988ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:02:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:02:39 | 401 |      1.4565ms |     172.40.0.13 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:02:45 | 200 |      37.827µs |      172.40.0.9 | GET      "/status"
[GIN] 2020/10/21 - 06:02:45 | 200 |      35.815µs |     172.40.0.10 | GET      "/status"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.784277ms |     172.40.0.12 | POST     "/api/v1/tokens"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.435579ms |     172.40.0.12 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.392785ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.432742ms |     172.40.0.11 | POST     "/api/v1/tokens"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.394848ms |     172.40.0.13 | POST     "/api/v1/tokens"
time="2020-10-21T06:03:39Z" level=warning msg="bearer token authorization failed; failed to parse given bearer token as valid JWT; Token is expired"
[GIN] 2020/10/21 - 06:03:39 | 401 |    1.457018ms |     172.40.0.13 | POST     "/api/v1/tokens"
[GIN] 2020/10/21 - 06:03:45 | 200 |      33.558µs |      172.40.0.9 | GET      "/status"
[GIN] 2020/10/21 - 06:03:45 | 200 |      48.855µs |     172.40.0.10 | GET      "/status"
`

Something seems to be wrong with the tokens being generated, but I have no idea what is causing it. Maybe an issue with certificates? But I have no idea to check sadly. 

On another node, I've tried this on 2 machines with 16GB of RAM. Could it be I'm running out of memory?

**Comment by kthomas** [comment]
@B45man -- `git checkout bri-1.1` -- make sure you pull the latest.

Run `docker system prune` -- then simply `npm install` and `npm test`.

**Comment by kthomas** [comment]
There is actually a commit that needs to be pushed to the `bri-1.1` branch which fixes the issue you are seeing above. The containers are now pinned to prevent introducing breaking changes.

**Comment by kthomas** [comment]
Fixed on `bri-1.1` branch as of `7ad4e78d18f9d51ff31813c7cb4bc95d9b49da64`.

@B45man ^^

**Comment by B45man** [comment]
Thanks a ton! I'm currently nowhere near a computer but will try later today.

**Comment by B45man** [comment]
Hey @kthomas , still no luck I'm afraid. I tried with the help of a coworker, and performed the following steps: 

1. Clear all old docker images, running containers, volumes and networks.
2. `git clone` the repo, start fresh.  
3. `git checkout bri-1.1`
4. Go to the folder `/core/privacy`, and run `npm install` and `npm run-script build` to build a missing package (package builds succesfully).
5.  Go to the folder `/examples/bri-1/base-example`, check to see if the file `src/index.ts` imports the package I build in step 4. the line is 
`import { IZKSnarkCircuitProvider, IZKSnarkCompilationArtifacts, IZKSnarkTrustedSetupArtifacts, zkSnarkCircuitProviderServiceFactory, zkSnarkCircuitProviderServiceZokrates, Element, elementify, rndHex, concatenateThenHash } from '../../../../core/privacy/dist/cjs' ` which looks good. 
6. In the folder `/examples/bri-1/base-example`, run `npm install` followed by `npm test`.

After this, the docker networks, volumes and containers are created without issue. The output is:

```
  baseline
    workgroup
      creation
        1) "before all" hook in "baseline"
TypeError: Cannot read property 'filename' of undefined
TypeError: Cannot read property 'filename' of undefined
        2) "before all" hook for "should create the workgroup in the local registry"
TypeError: Cannot read property 'filename' of undefined
TypeError: Cannot read property 'filename' of undefined
      participants
        3) "before all" hook in "participants"


  0 passing (1s)
  3 failing

  1) baseline
       "before all" hook in "baseline":
     Error: done() called multiple times in hook <baseline "before all" hook in "baseline"> of file /home/bas/Source/baseline/examples/bri-1/base-example/test/e2e.spec.ts; in addition, done() received error: { /home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index_bg.js:1
TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index_bg.js:3:78)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index.js:1) uncaught: true }
      at process.EventEmitter.emit (domain.js:448:20)
      at process.emit (node_modules/source-map-support/source-map-support.js:495:21)
      at process._fatalException (internal/bootstrap/node.js:497:27)
      at process.<anonymous> (node_modules/esm/esm.js:1:289374)
      at process.<anonymous> (node_modules/esm/esm.js:1:289220)
      at process.<anonymous> (node_modules/esm/esm.js:1:284879)
      at Object.apply (node_modules/esm/esm.js:1:199341)
      at fatalException (internal/process/promises.js:181:16)
      at emitPromiseRejectionWarnings (internal/process/promises.js:138:7)
      at process._tickCallback (internal/process/next_tick.js:69:34)

  2) baseline
       workgroup
         creation
           "before all" hook for "should create the workgroup in the local registry":
     Uncaught /home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index_bg.js:1
TypeError: Cannot read property 'filename' of undefined
      at Object.<anonymous> (/home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index_bg.js:3:78)
      at Generator.next (<anonymous>)
      at Generator.next (<anonymous>)
      at Object.<anonymous> (/home/bas/Source/baseline/core/privacy/node_modules/zokrates-js/pkg/index.js:1)

  3) baseline
       workgroup
         participants
           "before all" hook in "participants":
     AssertionError: workgroup should not be null
      at Context.before (test/e2e.spec.ts:153:9)
      at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by kthomas** [comment]
Fixes have been merged. Make sure you purge any old docker containers. Run `npm install` and `npm test` after.
