### ISSUE TITLE
api-buyer, api-supplier1, api-supplier2 fail to start

### ISSUE THREAD

**Issue by j4ys0n** [ethereum-oasis/baseline#29]
## Expected Behavior
containers should start

## Actual Behavior
containers crash

## Steps to Reproduce the Problem

  1. make
  1. make start

## Specifications

  - Version:
  - Platform: macOS 10.14, docker 2.2.0.4
  - Subsystem:

error:
```
api-buyer | /app/node_modules/config/lib/config.js:771
api-buyer | throw new Error('Config file ' + fullFilename + ' cannot be read. Error code is: '+e2.code
api-buyer | ^
api-buyer | Error: Config file /app/config/default.json cannot be read. Error code is: EISDIR. Error message is: EISDIR: illegal operation on a directory, read
api-buyer | at Config.util.parseFile (/app/node_modules/config/lib/config.js:771:13)
api-buyer | at /app/node_modules/config/lib/config.js:601:26
api-buyer | at Array.forEach (<anonymous>)
api-buyer | at Config.util.loadFileConfigs (/app/node_modules/config/lib/config.js:600:16)
api-buyer | at new Config (/app/node_modules/config/lib/config.js:116:27)
api-buyer | at Object.<anonymous> (/app/node_modules/config/lib/config.js:1436:31)
api-buyer | at Module._compile (internal/modules/cjs/loader.js:805:30)
api-buyer | at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
api-buyer | at Module.load (internal/modules/cjs/loader.js:672:32)
api-buyer | at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
api-buyer | at Function.Module._load (internal/modules/cjs/loader.js:604:3)
api-buyer | at Module.require (internal/modules/cjs/loader.js:711:19)
api-buyer | at require (internal/modules/cjs/helpers.js:14:16)
api-buyer | at Object.<anonymous> (/app/dist/utils/serverSettings.js:10:38)
api-buyer | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by bitwiseguy** [comment]
@j4ys0n The `deploy-contracts` script in the makefile creates those config files that are missing in your containers. I will open a PR to add that step to the `make start` script. In the meantime, you can try this sequence to hopefully get your environment up-and-running:
```
make
make deploy-contracts
make start
```

**Comment by j4ys0n** [comment]
`make deploy-contracts` is failing also. it creates the json files but fails in the next step.

```
✅  Uploaded verification key for createMSA. TxHash: 0x842f0828cf69e579ae8f1ebd5f46f680ea7938fce11cxxxxxxxxxx
(node:8) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at registerVerificationKey (/app/src/utils/vk.js:28:19)
    at uploadVks (/app/src/utils/vk.js:61:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/src/deploy.js:131:3)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lukedonato** [comment]
@j4ys0n Ran into this problem and fixed by increasing docker memory, swap memory, and CPU cores.

**Comment by j4ys0n** [comment]
@lukedonato what values do you have for those settings? it's still failing for me after increasing all of those.

**Comment by lukedonato** [comment]
@j4ys0n
I believe I had... CPUs: 8, Memory: 12GB, Swap: 4GB

**Comment by bitwiseguy** [comment]
I'm currently using the following:
- CPUs: 6
- Memory: 16GB
- Swap: 1GB

**Comment by lukedonato** [comment]
Apologies... I now remember after tracing this yesterday that the issue is actually with the "npm run setup" step. You will always receive that error if "npm run setup" does not generate the baseline/radish34/zkp/output/createMSA/createMSA_pk.key file.

**Comment by j4ys0n** [comment]
gotcha. so that's failing in the `make`/`make build` step?

**Comment by bitwiseguy** [comment]
@j4ys0n Yes that step is embedded inside `make build`. To only run that step, try `make zk-circuits`

**Comment by j4ys0n** [comment]
ok - `make zk-circuits` fixed `make deploy-contracts`. thank you!

there's still a problem with api-buyer & api-supplier1/2

```
Calling /start(Shield)
Got a polling error "Error: connect ECONNREFUSED 172.22.0.11:80", but that might be because the external server missed our call - we'll poll again...
...
```

this results in the front end (http://radish34-ui.docker/) showing "Error", It's getting a 404 from the graphql websocket.

**Comment by bitwiseguy** [comment]
Ok that looks like an issue with the `zkp` service. I suspect `docker logs radish_zkp_1` is showing an error. Might want to try the following sequence to get a fresh start:
```
docker-compose down
docker volume rm radish34_mongo-buyer radish34_mongo-supplier1 radish34_mongo-supplier2 radish34_mongo-merkle-tree-volume radish34_chaindata
docker-compose build zkp

make deploy-contracts
make start
```
Since you just created the zkp circuits for the first time, I think you need to rebuild that `zkp` container so that those circuit files are pulled in.

**Comment by j4ys0n** [comment]
Still not doing it. The UI still says "Error". The first couple calls to graphql result in `405: not allowed` and subsequent calls result in `404`.

I tried completely blowing out all caches and volumes in docker, running `make clean` then `make build`, `make deploy-contracts` and `make start`. I watched pretty closely and didn't see any errors in the build process.

The only things I can find that might be relevant are:
```
api-buyer | Calling /start(Shield)
api-buyer | Response from merkle-tree microservice for Shield:
api-buyer | { message:
api-buyer | 'filter is already in the process of being started for Shield' }
```
and a couple node errors:
```
geth-miner1 | ERROR[03-20|20:23:07.580] Unavailable modules in HTTP API list unavailable=[db] available="[admin debug web3 eth txpool personal clique miner net shh]"
geth-miner2 | ERROR[03-20|20:23:09.607] Unavailable modules in HTTP API list unavailable=[db] available="[admin debug web3 eth txpool personal clique miner net shh]"
geth-node | ERROR[03-20|20:23:11.284] Unavailable modules in HTTP API list unavailable=[db] available="[admin debug web3 eth txpool personal clique miner net shh]"
```

**Comment by j4ys0n** [comment]
Update, I tried again on another machine. Only differences being more RAM and macOS 10.15. The UI now loads. I'll try again on this machine. Thinking starting fresh will work. Thank you!

**Comment by bitwiseguy** [comment]
This should be fixed now that PR https://github.com/ethereum-oasis/baseline/pull/42 is merged
